### Register
POST  http://localhost:3000/api/register
Content-Type: application/json

    {
        "name":"peter",
        "email":"peter@gmail.com",
        "contact_phone":"0748200233",
        "password":"12345"
    }

###login
POST  http://localhost:3000/api/login
Content-Type: application/json

    {
        "email":"peter@gmail.com",
        "password":"12345"
    }

### Get all users
GET  http://localhost:3000/api/users?limit=1&details=true

### Get one users
GET  http://localhost:3000/api/users/1

### UPdate one user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

    {
        "name":"phantom",
        "email":"peter@gmail.com",
        "contact_phone":"0748200233",
        "password":"12345"
    }
### Delete one user
DELETE  http://localhost:3000/api/users/1


###Vehicles
POST http://localhost:3000/api/vehicles
Content-Type: application/json

    {
        "rental_rate": 5.5,
        "availability":true
    }

### get vehicle
GET  http://localhost:3000/api/vehicles?limit=1&details=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwicm9sZSI6InVzZXIiLCJlbWFpbCI6InBldGVyQGdtYWlsLmNvbSIsImV4cCI6MTcyMDMxMTA1N30.yV4eYNZ3y665V2yijoKY3nwfmTjN032_T0KZ5zdOyuI

### get one vehicle
GET  http://localhost:3000/api/vehicles/1?details=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwicm9sZSI6InVzZXIiLCJlbWFpbCI6InBldGVyQGdtYWlsLmNvbSIsImV4cCI6MTcyMDMxMTA1N30.yV4eYNZ3y665V2yijoKY3nwfmTjN032_T0KZ5zdOyuI

### update vehicles details
PUT http://localhost:3000/api/vehicles/1
Content-Type: application/json

    {
        "rental_rate": 7.5,
        "availability":true
    }
###delet vehicles details
DELETE  http://localhost:3000/api/vehicles/1

### get Vehicle-specific information
GET  http://localhost:3000/api/vehicle-spects?limit=2&&details=true

### get one car details specific
GET  http://localhost:3000/api/vehicle-spects/2?details=true

### delete one car vehicle details specific
DELETE  http://localhost:3000/api/vehicle-spects/1

###update one vehicle specific details
PUT http://localhost:3000/api/vehicle-spects/1
Content-Type: application/json

    {
        "manufacturer":"toyota",
        "model":"corolla",
        "year":2018,
        "color":"blue",
        "fuel_type":"petrol",
        "engine_capacity":"10",
        "transmission_capacity":"auto",
        "seating_capacity":"11"
    }

### create vehicle spects
POST http://localhost:3000/api/vehicle-spects
Content-Type: application/json

    {
        "vehicle_specsTable_id":1,
        "manufacturer":"toyota",
        "model":"corolla",
        "year":2018,
        "color":"blue",
        "fuel_type":"petrol",
        "engine_capacity":"10",
        "transmission_capacity":"manual",
        "seating_capacity":"10"
    }


### locations
GET  http://localhost:3000/api/location


### vehicles
GET  http://localhost:3000/api/vehicles