### Register
POST  http://localhost:3000/api/register
Content-Type: application/json

    {
        "name":"peter",
        "email":"peter@gmail.com",
        "contact_phone":"0748200233",
        "password":"12345"
    }

###login
POST  http://localhost:3000/api/login
Content-Type: application/json

    {
        "email":"peter@gmail.com",
        "password":"12345"
    }

### Get all users
GET  http://localhost:3000/api/users?limit=1&details=true

### Get one users
GET  http://localhost:3000/api/users/1

### UPdate one user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

    {
        "name":"phantom",
        "email":"peter@gmail.com",
        "contact_phone":"0748200233",
        "password":"12345"
    }
### Delete one user
DELETE  http://localhost:3000/api/users/1


###Vehicles
POST http://localhost:3000/api/vehicles
Content-Type: application/json

    {
        "rental_rate": 5.5,
        "availability":true,
        "location_id": 2
    }

### get vehicle
GET  http://localhost:3000/api/vehicles?details=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoidXNlciIsImVtYWlsIjoicGV0ZXJAZ21haWwuY29tIiwiZXhwIjoxNzIwMzIxOTUwfQ.C_iL5GQMsbiJrLBSSyJcfcjKe0V0WYXHaX34mKcZiOk

### get one vehicle
GET  http://localhost:3000/api/vehicles/2?details=true
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJyb2xlIjoidXNlciIsImVtYWlsIjoicGV0ZXJAZ21haWwuY29tIiwiZXhwIjoxNzIwMzIxOTUwfQ.C_iL5GQMsbiJrLBSSyJcfcjKe0V0WYXHaX34mKcZiOk

### update vehicles details
PUT http://localhost:3000/api/vehicles/1
Content-Type: application/json

    {
        "rental_rate": 7.5,
        "availability":true
    }
###delet vehicles details
DELETE  http://localhost:3000/api/vehicles/1

### get Vehicle-specific information
GET  http://localhost:3000/api/vehicle-spects?limit=2&&details=true

### get one car details specific
GET  http://localhost:3000/api/vehicle-spects/2?details=true

### delete one car vehicle details specific
DELETE  http://localhost:3000/api/vehicle-spects/1

###update one vehicle specific details
PUT http://localhost:3000/api/vehicle-spects/1
Content-Type: application/json

    {
        "manufacturer":"toyota",
        "model":"corolla",
        "year":2018,
        "color":"blue",
        "fuel_type":"petrol",
        "engine_capacity":"10",
        "transmission_capacity":"auto",
        "seating_capacity":"11"
    }

### create vehicle spects
POST http://localhost:3000/api/vehicle-spects
Content-Type: application/json

    {
        "vehicle_specsTable_id":1,
        "manufacturer":"toyota",
        "model":"corolla",
        "year":2018,
        "color":"blue",
        "fuel_type":"petrol",
        "engine_capacity":"10",
        "transmission_capacity":"manual",
        "seating_capacity":"10"
    }


### locations
GET  http://localhost:3000/api/location?limit=1&details=true

###get one location
GET  http://localhost:3000/api/location/2?details=true


### create location
POST  http://localhost:3000/api/location
Content-Type: application/json

    {
        "name":"nyeri",
        "address":"379nyeri",
        "contact":"08200312"
    }
###delete location
DELETE  http://localhost:3000/api/location/1

### fleet 
POST http://localhost:3000/api/fleet
Content-Type: application/json

    {
        "vehicle_id": 2,
        "acquisition_date":"2015-12-07",
        "depreciation_date":"2015-12-07",
        "maintances_cost":300.23,
        "status": "old"
    }


###get all fleet
GET  http://localhost:3000/api/fleet?details=true

###get one fleet
GET  http://localhost:3000/api/fleet/1?details=true

###update one fleet
PUT http://localhost:3000/api/fleet/1
Content-Type: application/json

    {
        "vehicle_id": 2,
        "acquisition_date":"2015-12-07",
        "depreciation_date":"2015-12-07",
        "maintances_cost":300.23,
        "status": "new"
    }

###delete one fleet
DELETE  http://localhost:3000/api/fleet/1


###support message
GET  http://localhost:3000/api/support?details=true & limit =1

###get one support message
GET  http://localhost:3000/api/support/1?details=true

### create new support message
POST  http://localhost:3000/api/support
Content-Type: application/json

    {
        "user_id":2,
        "subject":"delay for my next hire",
        "description":"I need to delay my next hire for 2 days",
        "status":"pending"
    }

###update one support message
PUT http://localhost:3000/api/support/1
Content-Type: application/json

    {
        "user_id":2,
        "subject":"delay for hire",
        "description":"I need to delay my next hire for 2 days",
        "status":"pending"
    }


### booking
GET  http://localhost:3000/api/bookings?details=true

###get one booking
GET  http://localhost:3000/api/bookings/1?details=true

### create new booking
POST  http://localhost:3000/api/bookings
Content-Type: application/json

    {
        "user_id":2,
        "vehicle_id":2,
        "location_id":2,
        "booking_date":"2015-12-07",
        "return_date":"2015-12-07",
        "totalAmount":"200",
        "status":"pending"
    }

###update one booking
PUT http://localhost:3000/api/bookings/1
Content-Type: application/json

    {
        "user_id":2,
        "vehicle_id":2,
        "location_id":2,
        "booking_date":"2015-12-07",
        "return_date":"2015-12-07",
        "totalAmount":"200",
        "status":"returned"
    }


###delete one booking
DELETE  http://localhost:3000/api/bookings/1


### payment 
POST http://localhost:3000/api/payment
Content-Type: application/json

    {
        "booking_id":1,
        "amount":"200",
        "payment_status":"pending",
        "payment_date":"2015-12-07",
        "payment_method":"safaricom",
        "trasaction_id":"1234567890"
    }

###get one payment
GET  http://localhost:3000/api/payment/2?details=true

### get all payments
GET  http://localhost:3000/api/payment?details=true

###update payment
PUT http://localhost:3000/api/payment/2
Content-Type: application/json

    {
        "booking_id":1,
        "amount":"300",
        "payment_status":"pending",
        "payment_date":"2015-12-07",
        "payment_method":"safaricom",
        "trasaction_id":"123456789"
    }